version: '3.8'
services:
  # Semgrep issue https://sg.run/e4JE
  # Ignore reason: The docker compose is not being used to deploy, it's mainly for local testing
  # nosemgrep
  cache:
    image: redis:7.0.15-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
