/*
 *  Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

import { bucketNameParameter, eventBusNameParameter } from '@agie/cdk-common';
import * as cdk from 'aws-cdk-lib';
import { StackProps } from 'aws-cdk-lib';
import { IVpc } from 'aws-cdk-lib/aws-ec2';
import { StringParameter } from 'aws-cdk-lib/aws-ssm';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';
import { userPoolClientIdParameter, userPoolIdParameter } from '../shared/cognito.construct.js';
import { verifiedPermissionsPolicyStoreIdParameter } from '../shared/verifiedPermissions.construct.js';
import { EngineConstruct } from './engine.construct.js';

export type EngineStackProperties = StackProps & {
	readonly environment: string;
	readonly vpc: IVpc;
	readonly stacApiEndpoint: string;
	readonly stacApiResourceArn: string;
	readonly sentinelApiUrl: string;
	readonly sentinelCollection: string;
};

export class EngineStack extends cdk.Stack {
	constructor(scope: Construct, id: string, props?: EngineStackProperties) {
		super(scope, id, props);

		const eventBusName = StringParameter.fromStringParameterAttributes(this, 'eventBusName', {
			parameterName: eventBusNameParameter(props.environment),
			simpleName: false,
		}).stringValue;

		const bucketName = StringParameter.fromStringParameterAttributes(this, 'bucketName', {
			parameterName: bucketNameParameter(props.environment),
			simpleName: false,
		}).stringValue;

		const policyStoreId = StringParameter.fromStringParameterAttributes(this, 'policyStoreId', {
			parameterName: verifiedPermissionsPolicyStoreIdParameter(props.environment),
			simpleName: false,
		}).stringValue;

		const cognitoClientId = StringParameter.fromStringParameterAttributes(this, 'clientId', {
			parameterName: userPoolClientIdParameter(props.environment),
			simpleName: false,
		}).stringValue;

		const cognitoUserPoolId = StringParameter.fromStringParameterAttributes(this, 'userPoolId', {
			parameterName: userPoolIdParameter(props.environment),
			simpleName: false,
		}).stringValue;

		new EngineConstruct(this, 'EngineModule', {
			vpc: props.vpc,
			environment: props.environment,
			eventBusName,
			bucketName,
			stacApiEndpoint: props.stacApiEndpoint,
			stacApiResourceArn: props.stacApiResourceArn,
			sentinelApiUrl: props.sentinelApiUrl,
			sentinelCollection: props.sentinelCollection,
			cognitoClientId,
			cognitoUserPoolId,
			policyStoreId,
		});

		NagSuppressions.addResourceSuppressionsByPath(
			this,
			['/EngineModule/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/Resource'],
			[
				{
					id: 'AwsSolutions-IAM4',
					appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
					reason: 'This policy attached to the role is generated by CDK.',
				},
				{
					id: 'AwsSolutions-IAM5',
					appliesTo: ['Resource::*'],
					reason: 'This resource condition in the IAM policy is generated by CDK, this only applies to logs:DeleteRetentionPolicy and logs:PutRetentionPolicy actions.',
				},
			],
			true
		);

		NagSuppressions.addResourceSuppressionsByPath(
			this,
			['/EngineModule/Custom::DynamodbSeederCustomDynamodbSeeder'],
			[
				{
					id: 'AwsSolutions-IAM4',
					appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
					reason: 'This lambda policy and its associated role are generated by CDK.',
				},
				{
					id: 'AwsSolutions-L1',
					reason: 'Waiting for 3rd party to update the run time.',
				},
			],
			true
		);
	}
}
