import type { GroupDetails, RegionDetails } from '../results/models.js';
import { EngineJobDetails, polygonProcessingDetails } from "../results/models.js";

type EventType = 'created' | 'updated' | 'deleted';

type ResourceType = 'polygons' | 'groups' | 'regions' | 'states' | 'job';

export interface DomainEvent<T> {
	resourceType: ResourceType;
	eventType: EventType;
	id: string;
	old?: T;
	new?: T;
	error?: Error;
}

export const AWS_EVENT_BRIDGE_SCHEDULED_EVENT_SOURCE: string = 'aws.events';
export const ARCADE_EVENT_SOURCE: string = 'com.aws.arcade';
export const RESULTS_EVENT_SOURCE: string = 'com.aws.arcade.results';
export const ENGINE_EVENT_SOURCE: string = 'com.aws.arcade.engine';
export const SCHEDULER_EVENT_SOURCE: string = 'com.aws.arcade.scheduler';

// Results module events
export const AWS_EVENT_BRIDGE_SCHEDULED_EVENT: string = 'Scheduled Event';

/**
 * List of events generated by the regions module
 */
export const REGIONS_EVENT_SOURCE: string = 'com.aws.arcade.regions';

export const REGIONS_GROUP_CREATED_EVENT = `${REGIONS_EVENT_SOURCE}>groups>created`;
export const REGIONS_GROUP_UPDATED_EVENT = `${REGIONS_EVENT_SOURCE}>groups>updated`;
export const REGIONS_GROUP_DELETED_EVENT = `${REGIONS_EVENT_SOURCE}>groups>deleted`;
export const REGIONS_REGION_CREATED_EVENT = `${REGIONS_EVENT_SOURCE}>regions>created`;
export const REGIONS_REGION_UPDATED_EVENT = `${REGIONS_EVENT_SOURCE}>regions>updated`;
export const REGIONS_REGION_DELETED_EVENT = `${REGIONS_EVENT_SOURCE}>regions>deleted`;
export const RESULTS_POLYGON_CREATED_EVENT = `${REGIONS_EVENT_SOURCE}>polygons>created`;
export const RESULTS_POLYGON_UPDATED_EVENT = `${REGIONS_EVENT_SOURCE}>polygons>updated`;
export const RESULTS_POLYGON_DELETED_EVENT = `${REGIONS_EVENT_SOURCE}>polygons>deleted`;

/**
 * List of events generated by the executor module
 */

export const EXECUTOR_EVENT_SOURCE: string = 'com.aws.arcade.executor';
export const EXECUTOR_JOB_CREATED_EVENT = `${EXECUTOR_EVENT_SOURCE}>job>created`;
export const EXECUTOR_JOB_UPDATED_EVENT = `${EXECUTOR_EVENT_SOURCE}>job>updated`;
export const EXECUTOR_POLYGON_METADATA_CREATED_EVENT = `${EXECUTOR_EVENT_SOURCE}>polygonMetadata>created`;


export interface groupChangeEvent {
	account: string;
	region: string;
	source: string;
	'detail-type': string;
	detail: DomainEvent<GroupDetails>;
}

export interface regionChangeEvent {
	account: string;
	region: string;
	source: string;
	'detail-type': string;
	detail: DomainEvent<RegionDetails>;
}

export interface resultsChangeEvent {
	account: string;
	region: string;
	source: string;
	'detail-type': string;
	detail: DomainEvent<EngineJobDetails>;
}

export interface polygonsProcessingEvent {
	account: string;
	region: string;
	source: string;
	'detail-type': string;
	detail: polygonProcessingDetails;
}

export type {
	groupChangeEvent as GroupChangeEvent,
	regionChangeEvent as RegionChangeEvent,
	resultsChangeEvent as ResultsChangeEvent,
	polygonsProcessingEvent as PolygonsProcessingEvent
};
